check:
  - thoth-build
build:
  base-image: "quay.io/thoth-station/s2i-minimal-notebook:v0.3.0"
  build-stratergy: Source
  registry: quay.io
  registry-org: modh
  registry-project: s2i-pytorch-notebook
  registry-secret: modh-pusher-secret
